name: "variable-test-1"
description: "state-mandated description"

inputs:
  message:
    description: "state-mandated description"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Show me what you got"
      shell: "bash"
      run: |
        echo "${{inputs.message}}"
