name: on-push

on:
  push:

jobs:
  main:
    runs-on: "ubuntu-latest"
    if: >
      github.event.action == 'push'
      && github.event.ref_name != 'main'
    steps:
      - run: "echo this step wasn\\'t skipped"
