name: on-push

on:
  push:

jobs:
  main:
    runs-on: "ubuntu-latest"
    if: >
      github.ref_name != 'main'
      && github.actor == 'michaelmosher'

    steps:
      - run: "echo this job wasn\\'t skipped because ref_name is ${{github.ref_name}} and actor is ${{github.actor}}"
