name: on-push

on:
  push:

jobs:
  otel-setup:
    uses: "./.github/workflows/otel-helper.yml"
    with:
      job-name: "OTel Setup"
    secrets: inherit

  real-work:
    needs: [otel-setup]
    runs-on: ubuntu-latest
    steps:
      - name: "Setup"
        id: "start"
        shell: "bash"
        run: echo "time=$(date --rfc-3339=ns)" >> $GITHUB_OUTPUT

      - name: "No really, real work is happening here."
        shell: "bash"
        run: "sleep 30"

    outputs:
      start-time: "${{ steps.start.outputs.time }}"

  troubleshoot:
    needs: [real-work]
    runs-on: ubuntu-latest
    steps:
      - name: "Does start-time exist?"
        run: "echo start-time = ${{ needs.real-work.outputs.start-time}}"

  otel-export:
    needs: [otel-setup, real-work]
    uses: "./.github/workflows/otel-helper.yml"
    with:
      job-name: "Real Work"
      start-time: "${{ needs.real-work.outputs.start-time }}"
      trace-ID: "${{ needs.otel-setup.outputs.trace-ID }}"
    secrets: inherit
