name: on-push

on:
  push:

jobs:
  main:
    runs-on: "ubuntu-latest"
    if: >
      github.ref_name == 'main'
      && github.actor == 'michaelmosher'

    steps:
      - run: "echo this job wasn\\'t skipped because ref_name is ${{github.ref_name}} and actor is ${{github.actor}}"

      - run: |
          echo "${{ github.event.created }}"

  test-matrix:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - realKey: "a value"
    steps:
      - run: "echo ${{ matrix.realKey }}"
      - run: "echo ${{ matrix.fakeKey }}"

  test-variables:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ github.ref }}"

      - name: "variable-test-1"
        uses: "./actions/variable-test-1"
        with:
          message: "runURL = $runURL"
        env:
          runURL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
